### PR TITLE
Packaged for meteor

### PR DESCRIPTION
**Pull request by kalarani**
As discussed in #64 
- Added the package.js that contains the package metadata. Feel free to update it with your meteor username for publishing.
- Ported tests according to meteor usage format. Tests are copied over from the test.js file and has couple of modifications
  - Have removed `require` statements for `assert` and `strftime`. These are included as part of the package as test dependencies.
  - Have changed the default `Time` variable to `new Date(1307470705067); // Tue, 07 Jun 2011 18:18:25 GMT`. Since I was running my tests in IST, i had to change this to be on the same date for testing.

I've tested this in my app by creating a symlink for the package. It works as expected :)

### CODE REVIEW

**Comment by kalarani** [comment]
@samsonjs were you able to test this out? Is there anything I'm missing?

**Comment by samsonjs** [comment]
@kalarani Duplicating the tests is not good as we would have to maintain 2 versions of them. Is there a way to detect meteor and skip the requires when it's detected in the same file? Forking a version of this for meteor might be an option as it's not a huge library.

The tests aren't very good right now, requiring specific time zones to work properly. That's an ongoing issue you can see in the other issues and pull requests here on GitHub, and since I'm not using JavaScript these days I don't have plans to work on them any time soon.

**Comment by boonya** [comment]
I am not really sure these change is really useful. I can add any js library to a meteor project using ordinar `npm install` syntax. Why do I really need to instal this library using `meteor install`? What profit it gives us?

**Comment by boonya** [comment]
Ahh... 7 years went since that )

**Comment by samsonjs** [comment]
Yeah this is very stale. I'll close it for now but if someone wants to work on Meteor support I'm not opposed to merging it.

**Pull request closed without merging**
