### PR TITLE
v0.9 rewrite - all about API and performance

### PR DESCRIPTION
**Pull request by samsonjs**
This pull request will form the basis of v0.9. It's based on @alexandrnikitin's pull request (#41) which rewrites most of the code to [greatly improve performance](http://jsperf.com/strftime-optimization) and cleans up the sprawling API as well.

@alexandrnikitin's original pull request is quoted below:

Hi all,

I want to initiate a discussion/review. I've made work on performance optimization. It gives ~20x boost in tests with defined date and ~10x with current date on Node.js. http://jsperf.com/strftime-optimization
I changed the API (#29) which looks like:

```javascript
    // by default
    var strftime = require('../strftimeV2');
    var strftimeLocalized = require('../strftimeV2').setLocaleTo(it_IT);
    var strftimeWithCustomTimezone = require('../strftimeV2').setTimezoneTo(customTimezone);
    var strftimeUTC = require('../strftimeV2').useUTC();
     var strftimeLocalizedUTC = require('../strftimeV2').setLocaleTo(it_IT).useUTC();

    strftime('%A');
    strftimeLocalized('%A');
    // etc
```

I rewrote almost all the code from scratch but it is pretty simple and easy to read. I adapted tests to new API but they need refactoring. Please spend some time to review the code. Looking forward to your feedback.

### CODE REVIEW

**Comment by alexandrnikitin** [comment]
@samsonjs Where are we right now? I don't want to push you but want to finish with that :bowtie:

**Comment by samsonjs** [comment]
Yeah it's crazy that I let this sit for so long 😔

Busy this weekend but I'll try to dig in next week.

**Comment by samsonjs** [comment]
Sorry for the delay. The tests are updated with the new API and things appear to work nicely. The readme needs to be updated but otherwise I think this is probably ready to merge and release as 0.9. In 1.0 the deprecated shims for the old API can be removed.

Thanks so much for your work on this. It's a huge improvement!

**Comment by samsonjs** [comment]
Time to merge this before it diverges further. The v0.8 branch should only get bug fixes now, and the next release will be 0.9. Thanks again @alexandrnikitin.

**Pull request merged**
